server:
  port: 8080

spring:
    datasource:
      driver-class-name: org.postgresql.Driver
      url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/marketplace}
      username: ${SPRING_DATASOURCE_USERNAME:main}
      password: ${SPRING_DATASOURCE_PASSWORD:123456}
      database-platform: org.hibernate.dialect.PostgreSQLDialect

    jpa:
      hibernate:
        ddl-auto: update
      show-sql: true
      properties:
        hibernate.dialect: org.hibernate.dialect.PostgreSQLDialect