server:
  port: 8080

spring:
  cloud:
    gateway:
      routes:
        - id: user
          uri: http://user-service:8080
          predicates:
            - Path=/user/auth/**
            - Path=/user/profile/**
        - id: notification
          uri: http://notification-service:8080
          predicates:
              - Path=/notification/messages/**
        - id: point-service
          uri: http://point-service:8080
          predicates:
            - Path=/point/info/**
            - Path=/point/goods/**